### ISSUE TITLE
Server Not Found

### ISSUE THREAD

**Issue by ptmuldoon** [olback/cah#94]
I am attempting to install and when I attempt to launch at port 5000, all I receive is a "Not Found" Error.

Is there a trick to getting the server to start?

**Comment by EriComic** [comment]
Uhhhh... Readme?

**Comment by ptmuldoon** [comment]
Well, thank you for the response, but still can not get it to start.

I did read the readme and the setup file for self hosting as well.  I cloned and installed the docker on Ubuntu Sever and also in Unraid.  I see the 2 dockers created in both servers and running, but just get a Not Found error in a web browser when hitting port 5000.

I'm not expert at this stuff, so not sure where I could be going wrong.  But thank you for getting back to me and help is appreciated.

**Comment by olback** [comment]
Turns out that when I re-wrote the setup script and the new documentation, I forgot to mention that you also need to run `scripts/angular.sh`. Should work after that.

**Comment by ptmuldoon** [comment]
Thank you!!

I think you have the best cah game out there, and with today's social distancing requirements, we could all use a good laugh.

Thanks!!

**Comment by olback** [comment]
Documentation is now updated. See #97
