### ISSUE TITLE
Missing Card Packs

### ISSUE THREAD

**Issue by ptmuldoon** [olback/cah#96]
After installing the game and accessing on Port 5000, I noticed I have no card packs to choose from to start a game.  Just indicates "Filter" in the box.    

I'm guessing possible/likely user error or permissions error in my setup, but unsure.  I do see the *.psql files on the data and sql directories.  And I was able to confirm the postgres docker has the database and tables.  But if I do try and run the postgres/install script manually I get an authentication error.
psql: FATAL:  Peer authentication failed for user "-d"

Thanks

**Comment by olback** [comment]
Are you running this in docker?

**Comment by ptmuldoon** [comment]
Perhaps I am going about it all wrong.  My main steps are:
1. Fresh Ubuntu Server Install
2. Install nodejs, docker, docker-compose, anglerjs and other dependencies.
3. git clone the game
3. cd to cah and run /scripts/setup.sh which seems to make the 2 dockers.
4. run the /scripts/angular.sh script
5.  Access the game at port 5000.    Just missing the cards.

Am i going about it all wrong?  I've always set up containers (proxmox) and VM's so moving to docker is still new.

**Comment by Betacookie** [comment]
I have the exact same problem. I dealt with a lot of issues I had setting up the server - beginners trouble - and now I don't have any card packs showing up even though they are in /postgres/data/.

**Comment by olback** [comment]
The issue here seems to be that in production mode, the origin has to be "cah.ninja:443". Changing `NODE_ENV` in `.env` to `dev` should get you up and running locally. Working on a fix...

**Comment by olback** [comment]
To get up and running from your current state, remove `.env` and re-run `scripts/setup.sh`. Follow [setup.md](setup.md) from step 5.

@ptmuldoon 
The reason you're getting an auth error is because when you run the postgres install script, no username or password is set. Setting `POSTGRES_USER` and `POSTGRES_PASSWORD` should work.
